name: rental_review_app
description: A rental property review application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.9.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # ← İKON AYARLAMASI İÇİN GEREKLİ

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png # ← LOGO PNG DOSYASI BURADA TANIMLANIYOR

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png" # ← LOGO PNG YOLU
