name: rental_review_app
description: A rental property review application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.9.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  intl: ^0.18.0
  google_fonts: ^4.0.4
  image_picker: ^1.1.2
  # ...existing code...
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1   # <-- EKLENDİ
# ...existing code...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_icon.png
    - assets/giris_ev.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
# ...existing code...
  firebase_core: ^2.30.0     # <-- EKLENDİ
  firebase_auth: ^4.17.8     # <-- EKLENDİ
  cloud_firestore: ^4.15.8   # <-- EKLENDİ
# ...existing code...